on: workflow_dispatch
name: Pull latest analysis data from SonarQube and decorate PR
jobs:
  build-docker-container:
    runs-on: ubuntu-latest
    name: Fetch SonarQube project data
    steps:
      - uses: actions/checkout@v2
      - name: Send request to api
        uses: pherms/github-action-pr-decoration
        inputs:
          host: https://sqplayground.xablu.com
          projectKey: MyProjectKey
          login: ${{secrets.SONARQUBE_TOKEN}}
      - name: Upload artefact
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: result.json
  process-result-file:
    runs-on: ubuntu-latest
    name: Process result file
    needs: build-docker-container
    steps:
      - uses: actions/checkout@v2
      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: result
          path: result.json
      - name: Process file
        uses: eddiejaoude/github-actions-reader-writer@v0.1
        with:
          json-file-path: 'result.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          columns: 2
          object-field-names: '[ "metric", "value" ]'
          html-cell: '<td align="center"><p>{{ metric }}"</p></td><td><p>{{ value }}</p></td>'